# Generated by Django 5.1.6 on 2025-03-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_teacherprofile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='department',
            field=models.CharField(blank=True, choices=[('commerce', 'Commerce'), ('computer_applications', 'Computer Applications'), ('social_work', 'Social Work'), ('communication_media', 'Communication and Media Studies'), ('applied_economics', 'Applied Economics'), ('business_admin', 'Business Administration')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='teacher_profiles/'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='qualification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
